name: Run Playwright Tests

on:
  schedule:
    # - cron: "*/5 * * * *" # Every 5 MINUTES
    - cron: "0 9 * * *" # Every day at 09:00 UTC
    - cron: "0 21 * * *" # Every day at 21:00 UTC
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cash: "npm"
          cash-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Install Allure CLI
        run: npm install allure-commandline

      - name: Verify allure version
        run: npx allure --version

      # - name: Clean old Allure results
      #   run: rm -rf allure-results allure-report

      - name: Run Playwright tests
        run: node utils/run-test.js --verbose
        continue-on-error: true

      - name: List allure results
        run: ls -alh allure-results

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
